spring:
  datasource:
    url: jdbc:mysql://localhost:3306/brian
    password: password
    username: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
